sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '14'
before_install:
  - npm i -g npm
script:
  - npm run build
after_success:
  - npm publish
